### ISSUE TITLE
FEATURE: push/pull between remotes without local roundtrip

### ISSUE THREAD

**Issue by jpmschuler** [sourcebroker/deployer-extended-media#8]
deployer-extended-media and deployer-extended-database are doing a clean job.

I have a common scenario which isn't covered and I wanted to get your thoughts on this:
We have most stages in the same secure network and thus a 
* pull from PRODUCTION and push to STAGING

from my system for media and db would result in a lot of traffic, as the DB dump itself is easily 2GB.
Thus, we don't download to local, but rather let PRODUCTION ssh into STAGING and copy the files that way.

This reduces traffic and increases speed dramatically.

Of course that would only work if on PRODUCTION there are established SSH credentials (i.e. an ssh key defined for the user which allows to SSH into STAGING), but IMHO this prerequisite is understandable and necessary.
Of course this won't be possible with disconnected remotes, like PRODUCTION and LOCAL-DDEV.

I gladly stick to my hotwired deployer 6 based own code, but as I could replace a lot of my stuff with your two extensions I just thought to ask if you see potential in this or regard is as out-of-scope as uncommon. 
A plausible and working way around is to have a CI runner in the same network running the commands from a dashboard, as then it is at least internal traffic.

**Comment by kszymukowicz** [comment]
If I understand you well I was doing similar flow in past already while making synchronisation of production to some "backup" instance.

IMO the point is to not use the `db:copy` and `media:copy` commands but run a `db:pull` and `media:pull` directly on the staging host that you want to synchronise. Or if you do not want to allow staging to access production with ssh access for security reason then you can use `db:push` and `media:push` form production to staging and trigger that with some wrap command in authorized_keys).

I hope this solves your problem - if not then plz give me some more details.

**Comment by jpmschuler** [comment]
Wow, okay that sounds marvellous, then I misunderstood current capabilities and it is much more powerful than I thought before. Sorry for the hassle. Will do some in-depth tests based on this.
